import"../../../ui/components/tree_outline/tree_outline.js";import*as e from"../../../core/common/common.js";import*as t from"../../../core/i18n/i18n.js";import*as r from"../../../core/sdk/sdk.js";import*as o from"../../../models/bindings/bindings.js";import*as a from"../../../ui/components/helpers/helpers.js";import*as s from"../../../ui/components/render_coordinator/render_coordinator.js";import*as d from"../../../ui/lit/lit.js";var i=`div.generic-sourcemap-entry{overflow-x:hidden;text-overflow:ellipsis;white-space:nowrap}div.outer-container{width:100%;height:100%;overflow-y:auto;padding:2px;box-sizing:border-box}div.sourcemap-script-entry{grid-template-columns:8fr 3fr 2fr;gap:10px;display:grid}div.sourcemap-history-entry{grid-template-columns:2fr 3fr;gap:10px;display:grid}div.sourcemap-script-entry > div,\ndiv.sourcemap-history-entry > div{text-overflow:ellipsis;overflow-x:hidden;user-select:text}\n/*# sourceURL=${import.meta.resolve("./SourceMapsTreeView.css")} */`;const n=new CSSStyleSheet;n.replaceSync(i);const{html:c}=d,p={statusExcludedByFilterSettings:"Excluded due to filter settings",statusNotAttempted:"Not attempted",statusNotLoaded:"Not loaded",statusNotLoadedDueToAuthorizationError:"Not loaded due to authorization error",statusNotLoadedDueToNotFound:"Not found",statusNotLoadedDueToOtherError:"Not loaded due to unknown error",statusLoadedFromSymbolServer:"Loaded from Symbol Server",statusLoadedFromCache:"Loaded from cache",statusLoadedFromSourceMapURL:"Loaded from sourceMapURL comment",targetTypeAuctionWorklet:"Auction worklet",targetTypeBrowser:"Browser",targetTypeDedicatedWorker:"Dedicated worker",targetTypeFrame:"Frame",targetTypeNode:"Node.js Process",targetTypeServiceWorker:"Service worker",targetTypeSharedWorker:"Shared worker",targetTypeTab:"Tab",targetTypeUnknown:"Unknown target"},u=t.i18n.registerUIStrings("panels/edge_sourcemaps_monitor/components/SourceMapsTreeView.ts",p),l=t.i18n.getLocalizedString.bind(void 0,u);class g extends HTMLElement{static litTagName=d.StaticHtml.literal`edge-devtools-sourcemaps-tree-view`;#e=this.attachShadow({mode:"open"});#t=!1;constructor(){super(),r.TargetManager.TargetManager.instance().observeModels(r.DebuggerModel.DebuggerModel,this,{scoped:!0}),r.TargetManager.TargetManager.instance().observeModels(r.EdgeSourceMapsModel.EdgeSourceMapsModel,this,{scoped:!0})}connectedCallback(){this.#e.adoptedStyleSheets=[n]}set displayScriptsWithoutURL(e){this.#t=e,this.#r()}get displayScriptsWithoutURL(){return this.#t}async#r(){await s.write("SourceMapsTreeView render",async()=>{const e=await this.#o(),t=c`
        <div class="outer-container">
          <devtools-tree-outline
              .data=${e}>
          </devtools-tree-outline>
        </div>
      `;d.render(t,this.#e,{host:this})})}#a=(e,t)=>c`<edge-devtools-sourcemaps-tree-node
                            .data=${e}>
                        </edge-devtools-sourcemaps-tree-node>`;#s=()=>{this.#r()};modelAdded(e){e instanceof r.DebuggerModel.DebuggerModel?e.addEventListener(r.DebuggerModel.Events.ParsedScriptSource,this.#s):e instanceof r.EdgeSourceMapsModel.EdgeSourceMapsModel&&e.addEventListener("SourceMapHistoryUpdated",this.#s)}modelRemoved(e){e instanceof r.DebuggerModel.DebuggerModel?e.removeEventListener(r.DebuggerModel.Events.ParsedScriptSource,this.#s):e instanceof r.EdgeSourceMapsModel.EdgeSourceMapsModel&&e.removeEventListener("SourceMapHistoryUpdated",this.#s)}async#o(){const e=r.TargetManager.TargetManager.instance(),t=[];for(const o of e.targets()){const e=o.model(r.EdgeSourceMapsModel.EdgeSourceMapsModel),a={id:`target:${o.id()}`,treeNodeData:{type:"target",target:o},children:async()=>{const t=o.model(r.DebuggerModel.DebuggerModel);return t?t.scripts().filter(e=>!!this.#t||Boolean(e.sourceURL)).map(t=>{let r=0;if(e){r=y(e.eventsForScript(t))}return{id:`script:${o.id()}:${t.scriptId}`,treeNodeData:{type:"script",script:t,status:r},children:async()=>{if(e){return e.eventsForScript(t).map((e,r)=>({id:`history:${o.id()}:${t.scriptId}:${r}`,treeNodeData:{type:"history-event",displayName:e.name,status:e.status,displayStatus:e.underlyingError?e.underlyingError:m(e.status)}}))}return[]}}}):[]}};t.push(a)}return{defaultRenderer:this.#a,tree:t}}}class h extends HTMLElement{static litTagName=d.StaticHtml.literal`edge-devtools-sourcemaps-tree-node`;#e=this.attachShadow({mode:"open"});#d;connectedCallback(){this.#e.adoptedStyleSheets=[n]}set data(e){this.#d=e,this.#r()}get data(){if(!this.#d)throw new Error("Not yet initialized.");return this.#d}#i(e){const t=function(e){switch(e.type()){case r.Target.Type.BROWSER:return l(p.targetTypeBrowser);case r.Target.Type.FRAME:return l(p.targetTypeFrame);case r.Target.Type.NODE:return l(p.targetTypeNode);case r.Target.Type.ServiceWorker:return l(p.targetTypeServiceWorker);case r.Target.Type.SHARED_WORKER:return l(p.targetTypeSharedWorker);case r.Target.Type.TAB:return l(p.targetTypeTab);case r.Target.Type.Worker:return l(p.targetTypeDedicatedWorker);case r.Target.Type.AUCTION_WORKLET:return l(p.targetTypeAuctionWorklet);default:return l(p.targetTypeUnknown)}}(e.treeNodeData.target),o=e.treeNodeData.target.targetInfo()?.title??c`${t}: ${e.treeNodeData.target.inspectedURL()}`;return c`
      <div
          class="generic-sourcemap-entry"
          >
            ${o}
      </div>
    `}#n(t){const r=this.#d.treeNodeData.script;if(r){const a=o.DebuggerWorkspaceBinding.DebuggerWorkspaceBinding.instance().uiSourceCodeForScript(r);a&&e.Revealer.reveal(a),t.stopPropagation()}}#c=e=>{this.#n(e)};#p=e=>{"Enter"===e.key&&this.#n(e)};#u(e){const t=m(e.treeNodeData.status);return c`
      <div
          class="generic-sourcemap-entry sourcemap-script-entry"
          @dblclick=${this.#c}
          @keydown=${this.#p}
          >
        <div title=${e.treeNodeData.script.sourceURL}>${e.treeNodeData.script.sourceURL}</div>
        <div title=${e.treeNodeData.script.hash}>${e.treeNodeData.script.hash}</div>
        <div title=${t}>${t}</div>
      </div>
    `}#l(e){return c`<div class="generic-sourcemap-entry sourcemap-history-entry">
      <div>${e.treeNodeData.displayName}</div>
      <div>${e.treeNodeData.displayStatus}</div>
    </div>`}#r(){if(!this.#d)throw new Error("Not yet initialized.");let e;switch(this.#d.treeNodeData.type){case"target":e=this.#i(this.#d);break;case"script":e=this.#u(this.#d);break;case"history-event":e=this.#l(this.#d);break;default:throw new Error("Should not be reached.")}d.render(e,this.#e,{host:this})}}function m(e){let t;switch(e){case 1:t=l(p.statusNotLoadedDueToAuthorizationError);break;case 2:t=l(p.statusNotLoadedDueToNotFound);break;case 3:t=l(p.statusNotLoadedDueToOtherError);break;case 5:t=l(p.statusLoadedFromSymbolServer);break;case 6:t=l(p.statusLoadedFromCache);break;case 7:t=l(p.statusLoadedFromSourceMapURL);break;case 8:t=l(p.statusNotAttempted);break;case 9:t=l(p.statusExcludedByFilterSettings);break;default:t=l(p.statusNotLoaded)}return t}function y(e){const t=[5,6,7],r=[1],o=e.find(e=>t.indexOf(e.status)>-1);if(o)return o.status;const a=e.find(e=>r.indexOf(e.status)>-1);return a?a.status:0}a.CustomElements.defineComponent("edge-devtools-sourcemaps-tree-view",g),a.CustomElements.defineComponent("edge-devtools-sourcemaps-tree-node",h);var S=Object.freeze({__proto__:null,SourceMapsTreeView:g});export{S as SourceMapsTreeView};
//# sourceMappingURL=components.js.map
