import*as e from"../../../ui/lit/lit.js";import{render as o,html as t}from"../../../ui/lit/lit.js";import*as n from"../../../ui/visual_logging/visual_logging.js";import*as r from"../../../core/common/common.js";import*as s from"../../../core/i18n/i18n.js";import"../../../ui/components/buttons/buttons.js";import*as i from"../../../ui/legacy/legacy.js";import"../../../ui/components/icon_button/icon_button.js";import*as l from"../../../ui/components/helpers/helpers.js";var a=`.element-reveal-icon{display:inline-block;width:20px;height:20px;mask-image:var(--image-file-select-element);background-color:var(--icon-default)}\n/*# sourceURL=${import.meta.resolve("././elementsPanelLink.css")} */`;class c extends HTMLElement{#e=this.attachShadow({mode:"open"});#o=()=>{};#t=()=>{};#n=()=>{};set data(e){this.#o=e.onElementRevealIconClick,this.#t=e.onElementRevealIconMouseEnter,this.#n=e.onElementRevealIconMouseLeave,this.#r()}#r(){this.#s()}#s(){o(t`
      <style>${a}</style>
      <span
        class="element-reveal-icon"
        jslog=${n.link("elements-panel").track({click:!0})}
        @click=${this.#o}
        @mouseenter=${this.#t}
        @mouseleave=${this.#n}></span>
      `,this.#e,{host:this})}}customElements.define("devtools-elements-panel-link",c);var d=Object.freeze({__proto__:null,ElementsPanelLink:c}),m=`.hide-issues-menu-btn{position:relative;display:flex;background-color:transparent;flex:none;align-items:center;justify-content:center;padding:0;margin:0 -2px 0 4px;overflow:hidden;border-radius:0;border:none;&:hover > devtools-icon{color:var(--icon-default-hover)}}\n/*# sourceURL=${import.meta.resolve("././hideIssuesMenu.css")} */`;const u={tooltipTitle:"Hide issues"},p=s.i18n.registerUIStrings("panels/issues/components/HideIssuesMenu.ts",u),g=s.i18n.getLocalizedString.bind(void 0,p);class h extends HTMLElement{#e=this.attachShadow({mode:"open"});#i=r.UIString.LocalizedEmptyString;#l=()=>{};set data(e){this.#i=e.menuItemLabel,this.#l=e.menuItemAction,this.#s()}onMenuOpen(e){e.stopPropagation();const o=this.#e.querySelector("devtools-button"),t=new i.ContextMenu.ContextMenu(e,{x:o?.getBoundingClientRect().left,y:o?.getBoundingClientRect().bottom});t.headerSection().appendItem(this.#i,()=>this.#l(),{jslogContext:"toggle-similar-issues"}),t.show()}onKeydown(e){"Enter"!==e.key&&"Space"!==e.key||e.stopImmediatePropagation()}#s(){o(t`
    <style>${m}</style>
    <devtools-button
      .data=${{variant:"icon",iconName:"dots-vertical",title:g(u.tooltipTitle)}}
      .jslogContext=${"hide-issues"}
      class="hide-issues-menu-btn"
      @click=${this.onMenuOpen}
      @keydown=${this.onKeydown}></devtools-button>
    `,this.#e,{host:this})}}customElements.define("devtools-hide-issues-menu",h);var v=Object.freeze({__proto__:null,HideIssuesMenu:h}),f=`:host{display:inline-block;contain:content}devtools-icon{margin-right:2px}span{--edge-dark-foreground-color:#000;--edge-tip-color:#b368c0;--edge-info-color:#cecece;--edge-warning-color:#f2c811;--edge-error-color:#e95223;border-radius:20px;display:flex;font-size:12px;line-height:12px;padding:4px 8px;--icon-color:var(--edge-dark-foreground-color);color:var(--edge-dark-foreground-color)}.error{background-color:var(--edge-error-color)}.info{background-color:var(--edge-info-color)}.tip{background-color:var(--edge-tip-color)}.warning{background-color:var(--edge-warning-color)}@media (forced-colors: active){.error,\n  .info,\n  .tip,\n  .warning{--icon-color:ButtonText;forced-color-adjust:none;background-color:transparent;color:ButtonText}}\n/*# sourceURL=${import.meta.resolve("././edgeSeverityPill.css")} */`;const w=new CSSStyleSheet;w.replaceSync(f);const{html:b}=e,y={tip:"Tip",info:"Info",warning:"Warning",error:"Error",tips:"Tips",warnings:"Warnings",errors:"Errors"},E=s.i18n.registerUIStrings("panels/issues/components/EdgeSeverityPill.ts",y),k=s.i18n.getLazilyComputedLocalizedString.bind(void 0,E),I=(e,o)=>{switch(e){case 3:return k(o?y.errors:y.error);case 1:return k(y.info);case 0:return k(o?y.tips:y.tip);case 2:return k(o?y.warnings:y.warning);default:throw new Error(`Unexpected severity: ${e}`)}};class x extends HTMLElement{static litTagName=e.StaticHtml.literal`edge-devtools-severity-pill`;shadow=this.attachShadow({mode:"open"});set data({severity:e}){this.render(e)}connectedCallback(){this.shadow.adoptedStyleSheets=[w]}render(o){const t=I(o);e.render(b`
      <span class=${(e=>{switch(e){case 3:return"error";case 1:return"info";case 0:return"tip";case 2:return"warning";default:throw new Error(`Unexpected severity: ${e}`)}})(o)}><devtools-icon .data=${(e=>{const o="14px",t={color:"#000",height:o,width:o};switch(e){case 3:return{iconName:"cross-circle",...t};case 1:return{iconName:"info",...t};case 0:return{iconName:"edge-small-tip",...t};case 2:return{iconName:"warning",...t};default:throw new Error(`Unexpected severity: ${e}`)}})(o)}></devtools-icon>${t()}</span>`,this.shadow,{host:this})}}l.CustomElements.defineComponent("edge-devtools-severity-pill",x);var S=Object.freeze({__proto__:null,SeverityPill:x,severityToLabel:I});export{S as EdgeSeverityPill,d as ElementsPanelLink,v as HideIssuesMenu};
//# sourceMappingURL=components.js.map
